In [1]:
import numpy as np

In [11]:
a=np.zeros([4,4])
b=np.ones([3,3])

In [12]:
c=a+b

ValueError: operands could not be broadcast together with shapes (4,4) (3,3) 

In [20]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [21]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
d[:,:1]

array([[1],
       [4],
       [7]])

In [29]:
d[[1,0,2]]

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [51]:
d=d.transpose(1,0)

In [52]:
d

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
e=np.where((np.arange(10)%2)==1,1,0)

In [50]:
(d>5).sum()

4

In [71]:
arr=np.random.randn(5,3)

In [72]:
arr

array([[-1.00685337,  1.03885179, -0.72475361],
       [-0.21281921, -0.15594525,  1.44063148],
       [-0.46674674,  1.67871023, -0.97574448],
       [ 0.26116822,  0.86555647,  0.07150582],
       [ 1.22796976,  0.55559085,  1.51020092]])

In [73]:
arr.sort(0)

In [74]:
arr

array([[-1.00685337, -0.15594525, -0.97574448],
       [-0.46674674,  0.55559085, -0.72475361],
       [-0.21281921,  0.86555647,  0.07150582],
       [ 0.26116822,  1.03885179,  1.44063148],
       [ 1.22796976,  1.67871023,  1.51020092]])

In [75]:
np.unique(d)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])